// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMH7DDwDYoBzRd4i6_fUsO-8dOk7-RQUg',
    appId: '1:357863269444:android:2570277d02cacbd82f8811',
    messagingSenderId: '357863269444',
    projectId: 'csi44-a2441',
    storageBucket: 'csi44-a2441.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT2KuX61LHU12JvlSjtpbUty0XUUzDWEg',
    appId: '1:357863269444:ios:39fdd21de54a3ba72f8811',
    messagingSenderId: '357863269444',
    projectId: 'csi44-a2441',
    storageBucket: 'csi44-a2441.appspot.com',
    iosClientId: '357863269444-bpt9oslnoo152v86roj6frdmd1j13kh4.apps.googleusercontent.com',
    iosBundleId: 'com.kesegotumisang.csi464',
  );
}
